/**
 * Kairos Backend API
 * This API provides endpoints for the Kairos Backend application.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param id 
 * @param title 
 * @param description 
 * @param category 
 * @param dateTime 
 * @param maxParticipants 
 * @param organizerId 
 * @param structureId 
 * @param sectors 
 * @param images 
 */
data class EventDTO (

    val id: kotlin.Any? = null,
    val title: kotlin.Any,
    val description: kotlin.Any,
    val category: kotlin.Any,
    val dateTime: kotlin.Any,
    val maxParticipants: kotlin.Any,
    val organizerId: kotlin.Any,
    val structureId: kotlin.Any,
    val sectors: kotlin.Any,
    val images: kotlin.Any? = null
) {
}