/**
 * Kairos Backend API
 * This API provides endpoints for the Kairos Backend application.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import androidx.room.Entity
import androidx.room.PrimaryKey


/**
 *
 * @param id
 * @param title
 * @param description
 * @param category
 * @param dateTime
 * @param maxParticipants
 * @param organizerId
 * @param structureId
 * @param sectors
 * @param images
 */
@Entity(tableName = "events")
data class EventDTO(

    @PrimaryKey val id: kotlin.String,
    val title: kotlin.String,
    val description: kotlin.String,
    val category: kotlin.String,
    val dateTime: kotlin.String,
    val maxParticipants: kotlin.Int,
    val organizerId: kotlin.String,
    val structureId: kotlin.String,
    val sectors: List<SectorDTO>,
    val images: List<String>? = null
) {
}
