/**
 * Kairos Backend API
 * This API provides endpoints for the Kairos Backend application.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param title 
 * @param description 
 * @param category 
 * @param from 
 * @param to 
 * @param organizer 
 * @param structure 
 */
data class Filter (

    val title: kotlin.Any? = null,
    val description: kotlin.Any? = null,
    val category: kotlin.Any? = null,
    val from: kotlin.Any? = null,
    val to: kotlin.Any? = null,
    val organizer: kotlin.Any? = null,
    val structure: kotlin.Any? = null
) {
}