/**
 * Kairos Backend API
 * This API provides endpoints for the Kairos Backend application.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.PageableObject
import io.swagger.client.models.SortObject

/**
 * 
 * @param totalPages 
 * @param totalElements 
 * @param last 
 * @param pageable 
 * @param first 
 * @param numberOfElements 
 * @param size 
 * @param content 
 * @param number 
 * @param sort 
 * @param empty 
 */
data class PageWishlistDTO (

    val totalPages: kotlin.Any? = null,
    val totalElements: kotlin.Any? = null,
    val last: kotlin.Any? = null,
    val pageable: PageableObject? = null,
    val first: kotlin.Any? = null,
    val numberOfElements: kotlin.Any? = null,
    val size: kotlin.Any? = null,
    val content: kotlin.Any? = null,
    val number: kotlin.Any? = null,
    val sort: SortObject? = null,
    val empty: kotlin.Any? = null
) {
}