/**
 * Kairos Backend API
 * This API provides endpoints for the Kairos Backend application.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.SortObject

/**
 * 
 * @param unpaged 
 * @param paged 
 * @param pageNumber 
 * @param pageSize 
 * @param offset 
 * @param sort 
 */
data class PageableObject (

    val unpaged: kotlin.Any? = null,
    val paged: kotlin.Any? = null,
    val pageNumber: kotlin.Any? = null,
    val pageSize: kotlin.Any? = null,
    val offset: kotlin.Any? = null,
    val sort: SortObject? = null
) {
}