/**
 * Kairos Backend API
 * This API provides endpoints for the Kairos Backend application.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param timestamp 
 * @param url 
 * @param message 
 */
data class ServiceError (

    val timestamp: kotlin.Any? = null,
    val url: kotlin.Any? = null,
    val message: kotlin.Any? = null
) {
}