/**
 * Kairos Backend API
 * This API provides endpoints for the Kairos Backend application.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param unsorted 
 * @param sorted 
 * @param empty 
 */
data class SortObject (

    val unsorted: kotlin.Any? = null,
    val sorted: kotlin.Any? = null,
    val empty: kotlin.Any? = null
) {
}