/**
 * Kairos Backend API
 * This API provides endpoints for the Kairos Backend application.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.Sector
import io.swagger.client.models.Structure

/**
 * 
 * @param id 
 * @param structure 
 * @param sector 
 * @param capacity 
 */
data class StructureSector (

    val id: kotlin.Any? = null,
    val structure: Structure? = null,
    val sector: Sector? = null,
    val capacity: kotlin.Any? = null
) {
}