/**
 * Kairos Backend API
 * This API provides endpoints for the Kairos Backend application.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.Address
import io.swagger.client.models.StructureImage

/**
 * 
 * @param createdBy 
 * @param creationDate 
 * @param lastModifiedBy 
 * @param lastModifiedDate 
 * @param id 
 * @param name 
 * @param address 
 * @param country 
 * @param structureImage 
 * @param structureSectors 
 */
data class Structure (

    val createdBy: kotlin.Any? = null,
    val creationDate: kotlin.Any? = null,
    val lastModifiedBy: kotlin.Any? = null,
    val lastModifiedDate: kotlin.Any? = null,
    val id: kotlin.Any? = null,
    val name: kotlin.Any? = null,
    val address: Address? = null,
    val country: kotlin.Any,
    val structureImage: StructureImage? = null,
    val structureSectors: kotlin.Any? = null
) {
}