/**
 * Kairos Backend API
 * This API provides endpoints for the Kairos Backend application.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.Address
import io.swagger.client.models.StructureImage

/**
 * 
 * @param id 
 * @param name 
 * @param address 
 * @param country 
 * @param structureImage 
 */
data class StructureCreateDTO (

    val id: kotlin.Any,
    val name: kotlin.Any,
    val address: Address,
    val country: kotlin.Any,
    val structureImage: StructureImage
) {
}