/**
 * Kairos Backend API
 * This API provides endpoints for the Kairos Backend application.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param firstName 
 * @param lastName 
 * @param username 
 * @param email 
 * @param password 
 * @param role 
 * @param provider 
 * @param phoneNumber 
 */
data class UserCreateDTO (

    val firstName: kotlin.Any,
    val lastName: kotlin.Any,
    val username: kotlin.Any,
    val email: kotlin.Any,
    val password: kotlin.Any,
    val role: kotlin.Any? = null,
    val provider: kotlin.Any? = null,
    val phoneNumber: kotlin.Any? = null
) {
}