/**
 * Kairos Backend API
 * This API provides endpoints for the Kairos Backend application.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.UserImageDTO

/**
 *
 * @param id
 * @param firstName
 * @param lastName
 * @param username
 * @param email
 * @param phoneNumber
 * @param role
 * @param provider
 * @param profileImage
 */
data class UserDTO(

    val id: kotlin.String,
    val firstName: kotlin.String,
    val lastName: kotlin.String,
    val username: kotlin.String,
    val email: kotlin.String,
    val phoneNumber: kotlin.String? = null,
    val role: kotlin.String,
    val provider: kotlin.String,
    val profileImage: UserImageDTO? = null
) {
}