/**
 * Kairos Backend API
 * This API provides endpoints for the Kairos Backend application.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param name 
 * @param scope 
 * @param wishedEvents 
 * @param sharedUsers 
 */
data class WishlistUpdateDTO (

    val name: kotlin.Any? = null,
    val scope: kotlin.Any? = null,
    val wishedEvents: kotlin.Any? = null,
    val sharedUsers: kotlin.Any? = null
) {
}