/**
 * Kairos Backend API
 * This API provides endpoints for the Kairos Backend application.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param id 
 * @param name 
 * @param creationDate 
 * @param scope 
 * @param creator 
 * @param wishedEvents 
 * @param sharedUsers 
 */
data class WishlistDTO (

    val id: kotlin.Any,
    val name: kotlin.Any,
    val creationDate: kotlin.Any,
    val scope: kotlin.Any,
    val creator: kotlin.Any,
    val wishedEvents: kotlin.Any? = null,
    val sharedUsers: kotlin.Any? = null
) {
}